name: 04 - Using Actions

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Java and Maven
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          maven-version: '3.6.1'


      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: my-artifact

          
            
  
