name: 04 - Using Actions

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Java and Maven
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt' # or 'zulu', 'temurin', etc.
          java-version: 11
          java-package: jdk
          architecture: x64
          check-latest: false
          server-id: github
          server-username: ${{ secrets.GITHUB_ACTOR }}
          server-password: ${{ secrets.GITHUB_TOKEN }}
          overwrite-settings: true
          maven-version: 3.8.4 

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: my-artifact
