name: 05 - 2 - Event Filters and Activity Types

on:
  pull_request:
    types: [closed]
    branches:
      - master

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: Print Message for 2nd jaya branch
        run: echo "Running whenever a PR is closed"
