name: 06 - context
on: push
env:
 GLOBAL_VAR: "Available to all jobs"
jobs:
  job1:
    runs-on: ubuntu-latest
    env:
      JOB_VAR: "Available to this job only"

  example_job:
    runs-on: ubuntu-latest
    env:
      JOB_VAR: "job"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Use global variable
        run: echo "Global variable $GLOBAL_VAR"
      
      - name: Use job variable
        run: echo "Job variable $JOB_VAR"
      
      - name: Use step variable
        env:
          STEP_VAR: "step"
        run: |
          echo "Step variable $STEP_VAR"
          echo "Job variable  still $JOB_VAR"
          echo "Global variable still $GLOBAL_VAR"
